module "k8s_node_worker_3" {
  source         = "./modules/vm"
  vm_count       = var.k8s_node_worker_3["vm_count"]
  vmid           = var.k8s_node_worker_3["vmid"]
  target_node    = var.k8s_node_worker_3["target_node"]
  clone          = var.k8s_node_worker_3["clone"]
  name           = var.k8s_node_worker_3["vm_name"]
  cores          = var.k8s_node_worker_3["cores"]
  sockets        = var.k8s_node_worker_3["sockets"]
  cpu            = var.k8s_node_worker_3["cpu"]
  memory         = var.k8s_node_worker_3["memory"]
  disk_size      = var.k8s_node_worker_3["disk_size"]
  storage        = var.k8s_node_worker_3["storage"]
  network_model  = var.k8s_node_worker_3["network_model"]
  network_bridge = var.k8s_node_worker_3["network_bridge"]
  base_ip        = var.k8s_node_worker_3["base_ip"]
  ssh_key        = var.k8s_node_worker_3["ssh_key"]
  gateway        = var.k8s_node_worker_3["gateway"]
}