module "k8s_node_worker_2" {
  source = "./modules/vm"
  vm_count       = var.k8s_node_worker_2["vm_count"]
  vmid           = var.k8s_node_worker_2["vmid"]
  target_node    = var.k8s_node_worker_2["target_node"]
  clone          = var.k8s_node_worker_2["clone"]
  name           = var.k8s_node_worker_2["vm_name"]
  cores          = var.k8s_node_worker_2["cores"]
  sockets        = var.k8s_node_worker_2["sockets"]
  cpu            = var.k8s_node_worker_2["cpu"]
  memory         = var.k8s_node_worker_2["memory"]
  disk_size      = var.k8s_node_worker_2["disk_size"]
  storage        = var.k8s_node_worker_2["storage"]
  network_model  = var.k8s_node_worker_2["network_model"]
  network_bridge = var.k8s_node_worker_2["network_bridge"]
  base_ip        = var.k8s_node_worker_2["base_ip"]
  ssh_key        = var.k8s_node_worker_2["ssh_key"]
  gateway        = var.k8s_node_worker_2["gateway"]
}